# Generated by Django 4.0.3 on 2022-03-05 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='shopData',
        ),
    ]
