# Generated by Django 4.0.3 on 2022-03-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_data_shopdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comments',
        ),
        migrations.AlterField(
            model_name='shopdata',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
